### ISSUE TITLE
NullPointerException in XSSFColorConverter.getBorderColorCSS

### ISSUE THREAD

**Issue by lightoze** [vaadin/spreadsheet#567]
In 2.0.1 a block of code was added which accesses `color` variable before it is checked for null.
```
java.lang.NullPointerException
	at com.vaadin.addon.spreadsheet.XSSFColorConverter.getBorderColorCSS(XSSFColorConverter.java:125)
	at com.vaadin.addon.spreadsheet.SpreadsheetStyleFactory.borderStyles(SpreadsheetStyleFactory.java:1010)
	at com.vaadin.addon.spreadsheet.SpreadsheetStyleFactory.addCellStyleCSS(SpreadsheetStyleFactory.java:595)
	at com.vaadin.addon.spreadsheet.SpreadsheetStyleFactory.reloadWorkbookStyles(SpreadsheetStyleFactory.java:226)
	at com.vaadin.addon.spreadsheet.SpreadsheetFactory.loadWorkbookStyles(SpreadsheetFactory.java:364)
	at com.vaadin.addon.spreadsheet.SpreadsheetFactory.reloadSpreadsheetComponent(SpreadsheetFactory.java:276)
	at com.vaadin.addon.spreadsheet.SpreadsheetFactory.reloadSpreadsheetComponent(SpreadsheetFactory.java:248)
	at com.vaadin.addon.spreadsheet.Spreadsheet.read(Spreadsheet.java:2459)
```
As a result, some files cannot be opened at all.

**Comment by alvarezguille** [comment]
Thanks for reporting this, if you have a sample file reproducing the issue could you attach it? It'd make it much easier to add a regression test.

**Comment by lightoze** [comment]
[AUT-2017-06-28.xlsx](https://github.com/vaadin/spreadsheet/files/1105448/AUT-2017-06-28.xlsx)

**Comment by alvarezguille** [comment]
I was able to reproduce the issue with the file, once #568 is reviewed it should be fixed in next 2.x release.
For some reason after opening and saving the file with excel the workbook was fixed. Just out of curiosity, how was the xlsx file created?

**Comment by lightoze** [comment]
It was a template created with LibreOffice and then processed with Jxls. I'm not sure which is to blame - haven't tested the original template without processing.
