### ISSUE TITLE
Exception when using table filter

### ISSUE THREAD

**Issue by carlmcc** [vaadin/spreadsheet#635]
I get an exception trying to use a table filter in the attached "Parameter_File2_s1" workbook:
- select the "entity" tab
- in column A, click on the "Parameter" drop-down to trigger this error
`
java.lang.IllegalArgumentException: lastRow < firstRow || lastCol < firstCol
    at org.apache.poi.ss.util.CellRangeAddress.&lt;init&gt;(CellRangeAddress.java:52)
    at com.vaadin.addon.spreadsheet.SpreadsheetFilterTable.&lt;init&gt;(SpreadsheetFilterTable.java:94)
    at com.vaadin.addon.spreadsheet.SpreadsheetFilterTable.&lt;init&gt;(SpreadsheetFilterTable.java:70)
    at com.vaadin.addon.spreadsheet.SpreadsheetFactory.loadSheetTables(SpreadsheetFactory.java:455)
    at com.vaadin.addon.spreadsheet.SpreadsheetFactory.reloadSpreadsheetData(SpreadsheetFactory.java:410)
    at com.vaadin.addon.spreadsheet.Spreadsheet.setActiveSheetWithPOIIndex(Spreadsheet.java:1301)
    at com.vaadin.addon.spreadsheet.Spreadsheet.setActiveSheetIndex(Spreadsheet.java:1275)
    at com.vaadin.addon.spreadsheet.Spreadsheet.onSheetSelected(Spreadsheet.java:1323)
`

**Comment by johannesh2** [comment]
Thank you for the report. What version are you using?

**Comment by carlmcc** [comment]
Sorry, I forgot to say I'm using 1.4.0.alpha2, but the same error also occurs with the on-line spreadsheet demo, which is currently at 2.1.0.alpha1.

**Comment by alvarezguille** [comment]
@carlmcc, it looks like something happened and the attachment is missing, can you add it again?

**Comment by carlmcc** [comment]
[Parameter_File2_s1.xlsx](https://github.com/vaadin/spreadsheet/files/1447017/Parameter_File2_s1.xlsx)
